services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: meet_pallete
    ports:
      - "3307:3306"
    volumes:
      - ~/db_data/meet_pallete:/var/lib/mysql

  backend:
    image: tobeykwon/meet-pallete-backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql