spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/meet_palette
    username: kwon
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_size: 10

  batch:
    jdbc:
      initialize-schema: always

kakao:
  apiKey: 57e7f4f0262475875a9b94fcd8a97b3b

frontEndUrl:
  domain: "http://220.81.18.197:5173"
  placeConfirm: "${frontEndUrl.domain}/place-confirm/"

cool-sms:
  api-key: "NCSHUZ8V9NAHIDQ7"
  api-secret: "BRQ6IFOTVUMLDTMOWON8WQZGWZGP4VNF"
  sender-number: "01063230351"

